server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://user-db:3306/user_management
    username: root
    password: Eshu@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: user-group
      auto-offset-reset: earliest

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

user:
  kafka:
    topic: user-events
